"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { setLocalStorage, getLocalStorage } from "./storage-utils";

type Language = "mn" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  mn: {
    // Navigation
    "nav.home": "Нүүр",
    "nav.about": "Бидний тухай",
    "nav.dashboard": "Хяналтын самбар",
    "nav.tournaments": "Тэмцээнүүд",
    "nav.login": "Нэвтрэх",
    "nav.signup": "Бүртгүүлэх",
    "nav.logout": "Гарах",
    "nav.profile": "Профайл",
    "nav.notifications": "Мэдэгдэл",
    "nav.darkMode": "Харанхуй горим",
    "nav.lightMode": "Гэрэл горим",
    "nav.achievements": "Амжилт",
    
    // Home Page
    "home.title": "TemtseenPortal",
    "home.subtitle": "Монголын сурагчдад зориулсан олимпиад, тэмцээний систем",
    "home.description": "Математик, физик, хими болон бусад олимпиадад онлайнаар бүртгүүлж, амжилтаа хянаарай.",
    "home.studentTitle": "Сурагчийн хэсэг",
    "home.studentDesc": "Боломжтой тэмцээнүүдэд үзэж, бртгүүлж, өөрийн амжилтаа хянаарай",
    "home.organizerTitle": "Зохион байгуулагчийн хэсэг",
    "home.organizerDesc": "Тэмцээн үүсгэж, удирдаж, оролцогчдыг бүртгүүлээрэй",
    "home.features": "Онцлог боломжууд",
    "home.feature1": "Хялбар бүртгэл",
    "home.feature1Desc": "Хэдхэн дарцаар олимпиадад бүртгүүлээрэй",
    "home.feature2": "Найдвартай төлбөр",
    "home.feature2Desc": "Аюулгүй, найдвартай төлбөрийн систем",
    "home.feature3": "Мэдээлэл цаг тухайд нь",
    "home.feature3Desc": "Тэмцээний шинэчлэлтийг шуурхай хүлээн авах",
    "home.premierPlatform": "Монголын тэргүүлэх олимпиад платформ",
    "home.joinAsStudent": "Сурагч эсвэл зохион байгуулагчаар нэгдээрэй",
    "home.browseTournaments": "45+ тэмцээнийг үзнэ үү",
    "home.trackProgress": "Амжилт, хөгжлөө хянана уу",
    "home.earnAchievements": "Амжилтаа бүртгүүлэх",
    "home.manageTournaments": "Тэмцээнүүдийг удирдана уу",
    "home.trackRegistrations": "Бүртгэл, төлбөр хянана уу",
    "home.accessAnalytics": "Шинжилгээний мэдээллийг үзнэ үү",
    "home.getStarted": "Эхлэх",
    "home.learnMore": "Дэлгэрэнгүй",
    "home.readyToStart": "Эхлэхэд бэлэн үү?",
    "home.joinThousands": "Монголын тэргүүлэх олимпиад платформ дээр олон мянган сурагч, зохион байгуулагчдад нэгдээрэй",
    "home.chooseYourPath": "Таны замыг сонгоно уу",
    "home.students": "Сурагчид",
    "home.tournaments": "Тэмцээнүүд",
    "home.organizers": "Зохион байгуулагчид",
    "home.activeEvents": "Идэвхтэй тэмцээнүүд",
    "home.registrationFee": "Бүртгэлийн төлбөр",
    "home.easyRegistration": "Хялбар бүртгэл процесс",
    "home.trackAchievements": "Амжилтуудыг хянах",
    "home.createUnlimited": "Хязгааргүй тэмцээнүүд үүсгэх",
    "home.manageRegistrations": "Бүртгэлүүдийг удирдах",
    "home.analyticsDashboard": "Шинжилгээний мэдээллийн самбар",
    "home.createAccount": "Хэлбэр үүсгэх",
    "home.readyToGetStarted": "Эхлэхэд бэлэн үү?",
    
    // Student Dashboard
    "student.title": "Сурагчийн хяналтын самбар",
    "student.welcome": "Сайн байна уу",
    "student.availableTournaments": "Боломжтой тэмцээн",
    "student.myRegistrations": "Миний бүртгэл",
    "student.categories": "Ангилал",
    "student.allCategories": "Бүх ангилал",
    "student.search": "Тэмцээн хайх...",
    "student.noTournaments": "Тэмцээн олдсонгүй",
    "student.noRegistrations": "Бүртгэлтэй тэмцээн байхгүй байна",
    "student.noRegistrationsDesc": "Боломжтой тэмцээнээс сонгож бүртгүүлээрэй",
    "student.tryDifferentSearch": "Өөр нөхцлөөр хайж үзнэ үү",
    "student.registered": "Бүртгэлтэй",
    "student.full": "Дүүрсэн",
    "student.details": "Дэлгэрэнгүй",
    "student.register": "Бүртгүүлэх",
    "student.unregister": "Бүртгэл цуцлах",
    "student.finished": "Дууссан",
    "student.confirmUnregister": "Бүртгэлээ цуцлах уу?",
    "student.registrationFailed": "Бүртгэл амжилтгүй боллоо. Тэмцээн дүүрсэн байж магадгүй.",
    "student.grade": "анги",
    
    // Organizer Dashboard
    "organizer.title": "Зохион байгуулагчийн хяналтын самбар",
    "organizer.welcome": "Сайн байна уу",
    "organizer.myTournaments": "Миний тэмцээнүүд",
    "organizer.totalRegistrations": "Нийт бүргэл",
    "organizer.revenue": "Орлого",
    "organizer.createTournament": "Шинэ тэмцээн үүсгэх",
    "organizer.noTournaments": "Тэмцээн байхгүй байна",
    "organizer.createFirst": "Эхлээд тэмцээн үүсгээрэй",
    "organizer.edit": "Засах",
    "organizer.delete": "Устгах",
    "organizer.viewRegistrations": "Бүртгэлүүдийг харах",
    "organizer.confirmDelete": "Энэ тэмцээнийг устгах уу?",
    
    // Tournament Form
    "tournament.title": "Тэмцээний нэр",
    "tournament.description": "Тайлбар",
    "tournament.category": "Ангилал",
    "tournament.date": "Огноо",
    "tournament.location": "Байршил",
    "tournament.maxParticipants": "Хамгийн их оролцогч",
    "tournament.registrationFee": "Бүртгэлийн төлбөр (₮)",
    "tournament.pdfFile": "Бэлтгэл материал / Туршилтын тест (PDF)",
    "tournament.downloadMaterial": "Материал татах",
    "tournament.create": "Тэмцээн үүсгэх",
    "tournament.update": "Шинэчлэх",
    "tournament.cancel": "Цуцлах",
    
    // Tournament Detail
    "detail.tournamentDetails": "Тэмцээний дэлгэрэнгүй",
    "detail.about": "Тэмцээний тухай",
    "detail.organizer": "Зохион байгуулагч",
    "detail.registrationInfo": "Бүртгэлийн мэдээлэл",
    "detail.spotsLeft": "Үлдсэн орон зай",
    "detail.spots": "орон зай",
    "detail.payment": "Төлбөр",
    "detail.status": "Статус",
    "detail.open": "Нээлттэй",
    "detail.closed": "Хаагдсан",
    "detail.backToDashboard": "Хяналтын самбар руу буцах",
    "detail.notFound": "Тэмцээн олдсонгүй",
    "detail.notFoundDesc": "Таны хайсан тэмцээн олдсонгүй эсвэл устгагдсан байна",
    
    // Payment Modal
    "payment.title": "Бүртгэлийн төлбөр төлөх",
    "payment.tournament": "Тэмцээн",
    "payment.amount": "Дүн",
    "payment.cardNumber": "Картын дугаар",
    "payment.expiryDate": "Хүчинтэй хугацаа (ММ/ЖЖ)",
    "payment.cvv": "CVV",
    "payment.confirmPayment": "Төлбөр төлөх",
    "payment.processing": "Боловсруулж байна...",
    "payment.success": "Төлбөр амжилттай төлөгдлөө!",
    "payment.successMessage": "Та амжилттай бүртгэглээ.",
    "payment.error": "Төлбөр амжилтгүй боллоо",
    "payment.tryAgain": "Дахин оролдоно уу",
    
    // Auth
    "auth.studentLogin": "Сурагч нэвтрэх",
    "auth.organizerLogin": "Зохион байгуулагч нэвтрэх",
    "auth.email": "Имэйл",
    "auth.password": "Нууц үг",
    "auth.login": "Нэвтрэх",
    "auth.noAccount": "Бүртгэлгүй юу?",
    "auth.signupHere": "Энд бүртгүүлэх",
    "auth.invalidCredentials": "Имэйл эсвэл нууц үг буруу байна",
    "auth.studentSignup": "Сурагч бүртгүүлэх",
    "auth.organizerSignup": "Зохион байгуулагч бүртгүүлэх",
    "auth.name": "Нэр",
    "auth.school": "Сургууль",
    "auth.grade": "Анги",
    "auth.organization": "Байгууллага",
    "auth.signup": "Бүртгүүлэх",
    "auth.haveAccount": "Бүртгэлтэй юу?",
    "auth.loginHere": "Энд нэвтрэх",
    
    // Login/Signup Pages
    "login.title": "Нэвтрэх",
    "login.subtitle": "Өөрийн эрхээр нэвтрэх",
    "login.button": "Нэвтрэх",
    "login.error": "Имэйл эсвэл нууц үг буруу байна",
    "login.noAccount": "Бүртгэлгүй юу?",
    "login.signupLink": "Бүртгүүлэх",
    "login.role": "Хэрэглэгчийн төрөл",
    "login.welcomeBack": "Тавтай морил!",
    "login.demoAccounts": "Туршилтын бүртгэл:",
    "login.email": "Имэйл",
    "login.password": "Нууц үг",
    
    "signup.title": "Бүртгүүлэх",
    "signup.subtitle": "Шинэ эрх үүсгэх",
    "signup.button": "Бүртгүүлэх",
    "signup.error": "Энэ имэйл аль хэдийн бүртгэлтэй байна",
    "signup.hasAccount": "Бүртгэлтэй юу?",
    "signup.loginLink": "Нэвтрэх",
    "signup.role": "Хэрэглэгчийн төрөл",
    "signup.name": "Нэр",
    "signup.email": "Имэйл",
    "signup.password": "Нууц үг",
    "signup.school": "Сургууль",
    "signup.grade": "Анги",
    "signup.organization": "Байгууллага",
    
    // About Page
    "about.title": "Бидний тухай",
    "about.mission": "Бидний эрхэм зорилго",
    "about.missionText": "TemtseenPortal нь Монголын сурагчдад олимпиад, тэмцээнд хялбархан бүртүүлэх боломжийг олгохоор зорьж байна. Бид боловсролын салбарт дижитал шийдлээр дэмжлэг үзүүлж, сурагчдын ур чадварыг хөгжүүлэхэд хувь нэмэр оруулж байна.",
    "about.howItWorks": "Хэрхэн ажилладаг вэ?",
    "about.forStudents": "Сурагчдад",
    "about.forStudentsText": "Боломжтой тэмцээнүүдийг хайж олж, хэдхэн дарцаар бүртгүүлээрэй. Найдвартай төлбөрийн системээр бүртгэлийн төлбөрөө төлж, өөрийн амжилтаа хянаарай.",
    "about.forOrganizers": "Зохион байгуулагчдад",
    "about.forOrganizersText": "Тэмцээн үүсгэж, оролцогчдыг удирдаж, бүртгэлийн төлбөрийг хянаарай. Бүх процессыг нэг платформ дээр хялбараар удирдаарай.",
    "about.contact": "Холбоо барих",
    "about.contactText": "Асуулт, санал хүсэлт байвал бидэнтэй холбогдоорой:",
    "about.email": "Имэйл: temtseenportal@gmail.com",
    "about.phone": "Утас: +976 7000-0000",
    "about.description": "TemtseenPortal нь Монголын сурагчдад зориулсан олимпиад, тэмцээний бүртгэлийн платформ юм. Бид боловсролын салбарт орчин үеийн технологийн шийдэл авчирч байна.",
    "about.ourMission": "Манай эрхэм зорилго",
    "about.missionDesc": "TemtseenPortal нь Монголын сурагчдын авьяас чадварыг дэмжиж, тэдний хөгжилд хувь нэмрээ оруулахыг зорьж байна. Бид олимпиад, тэмцээний бүртгэл, удирдлагыг хялбар, найдвартай болгож, боловсролын салбарт шинэ чанарыг нэвтрүүлж байна.",
    "about.value1": "Сурагчдыг бүрэн чадавхжуулах",
    "about.value2": "Зохион байгуулагчдад хүчирхэг хэрэгсэл олгох",
    "about.value3": "Идэвхтэй боловсролын нийгэмлэг бүрдүүлэх",
    "about.students": "Сурагчид",
    "about.events": "Тэмцээн",
    "about.organizers": "Зохион байгуулагчид",
    "about.coreValues": "Үндсэн үнэт зүйлс",
    "about.coreValuesDesc": "Бидний үйл ажиллагааг удирдан чиглүүлдэг зарчмууд",
    "about.excellence": "Шилдэг байдал",
    "about.excellenceDesc": "Бид бүх зүйлдээ хамгийн өндөр түвшинг эрмэлздэг",
    "about.community": "Нийгэмлэг",
    "about.communityDesc": "Сурагч, зохион байгуулагчдын хоорондын харилцааг бэхжүүлэх",
    "about.innovation": "Шинэчлэл",
    "about.innovationDesc": "Платформоо шинэ боломжуудаар тасралтгүй сайжруулж байна",
    "about.achievement": "Амжилт",
    "about.achievementDesc": "Сурагчдын амжилтыг тэмдэглэж, шагнадаг",
    "about.builtForMongolia": "Монголд зориулж бүтээгдсэн",
    "about.builtForMongoliaDesc": "TemtseenPortal нь Монгол улсад, Монголын сурагч, багш нарт зориулж бүтээгдсэн платформ юм",
    "about.joinCommunity": "Манай өсөн нэмэгдэж буй нийгэмлэгт нэгдээрэй",
    "about.joinCommunityDesc": "Та тэмцээнд оролцох сурагч эсвэл тэмцээн зохион байгуулах хүн бай, TemtseenPortal танд туслахад бэлэн байна.",
    "about.getStarted": "Өнөөдөр эхэл",
    "about.backHome": "Нүүр хуудас руу буцах",
    
    // Footer
    "footer.copyright": "© 2026 TemtseenPortal. Монголын сурагчдад зориулсан олимпиад, тэмцээний бүртгэлийн систем",
    
    // Profile
    "profile.title": "Хувийн мэдээлэл",
    "profile.subtitle": "өрийн профайл мэдээллээ засаарай",
    "profile.back": "Буцах",
    "profile.edit": "Засах",
    "profile.save": "Хадгалах",
    "profile.saveChanges": "Өөрчлөлт хадгалах",
    "profile.cancel": "Цуцлах",
    "profile.saveSuccess": "Амжилттай хадгалагдлаа!",
    "profile.name": "Нэр",
    "profile.email": "Имэйл",
    "profile.phone": "Утас",
    "profile.school": "Сургууль",
    "profile.grade": "Анги",
    "profile.organization": "Байгууллага",
    "profile.address": "Хаяг",
    
    // Notifications
    "notifications.title": "Мэдэгдлүүд",
    "notifications.back": "Буцах",
    "notifications.unreadCount": "{count} уншаагүй мэдэгдэл",
    "notifications.noUnread": "Уншаагүй мэдэгдэл байхгүй",
    "notifications.markAllRead": "Бүгдийг унших",
    "notifications.clearAll": "Бүгдийг устгах",
    "notifications.all": "Бүгд",
    "notifications.unread": "Уншаагүй",
    "notifications.markRead": "Унших",
    "notifications.noNotifications": "Мэдэгдэл байхгүй байна",
    "notifications.noNotificationsDesc": "Та шинэ мэдэгдэл хүлээн авахад энд харагдана",
    "notifications.confirmClear": "Бүх мэдэгдлийг устгах уу?",
    "notifications.registrationSuccess": "Бүртгэл амжилттай!",
    "notifications.registrationSuccessMsg": "Та тэмцээнд амжилттай бүртгэгдлээ.",
    "notifications.tournamentReminder": "Тэмцээний сануулга",
    "notifications.tournamentReminderMsg": "Таны тэмцээн 3 өдрийн дараа эхэлнэ.",
    "notifications.paymentPending": "Төлбөр хүлээгдэж байна",
    "notifications.paymentPendingMsg": "Таны бүртгэлийн төлбөр төлөгдөөгүй байна.",
    "notifications.tournamentCreated": "Тэмцээн үүсгэгдлээ",
    "notifications.tournamentCreatedMsg": "Таны тэмцээн амжилттай үүсгэгдлээ.",
    
    // Achievements
    "achievements.title": "Миний амжилтууд",
    "achievements.subtitle": "Таны олимпиад, тэмцээний түүх",
    "achievements.back": "Буцах",
    "achievements.total": "Нийт",
    "achievements.gold": "Алт",
    "achievements.silver": "Мөнгө",
    "achievements.bronze": "Хүрэл",
    "achievements.avgPlace": "Дундаж байр",
    "achievements.allCategories": "Бүх ангилал",
    "achievements.noAchievements": "Амжилт байхгүй байна",
    "achievements.noAchievementsDesc": "Тэмцээнд оролцож, амжилт бүртгүүлээрэй",
    "achievements.first": "1-р байр",
    "achievements.second": "2-р байр",
    "achievements.third": "3-р байр",
    "achievements.place": "-р байр",
    "achievements.participants": "оролцогч",
    "achievements.score": "Оноо",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.dashboard": "Dashboard",
    "nav.tournaments": "Tournaments",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.logout": "Logout",
    "nav.profile": "Profile",
    "nav.notifications": "Notifications",
    "nav.darkMode": "Dark Mode",
    "nav.lightMode": "Light Mode",
    "nav.achievements": "Achievements",
    
    // Home Page
    "home.title": "TemtseenPortal",
    "home.subtitle": "Olympiad and Tournament System for Mongolian Students",
    "home.description": "Register online for math, physics, chemistry, and other olympiads, and track your progress.",
    "home.studentTitle": "For Students",
    "home.studentDesc": "Browse available tournaments, register, and track your achievements",
    "home.organizerTitle": "For Organizers",
    "home.organizerDesc": "Create and manage tournaments, register participants",
    "home.features": "Key Features",
    "home.feature1": "Easy Registration",
    "home.feature1Desc": "Register for olympiads with just a few clicks",
    "home.feature2": "Secure Payments",
    "home.feature2Desc": "Safe and reliable payment system",
    "home.feature3": "Real-time Updates",
    "home.feature3Desc": "Receive tournament updates instantly",
    "home.premierPlatform": "Premier Olympiad Platform for Mongolia",
    "home.joinAsStudent": "Join as a student or organizer",
    "home.browseTournaments": "Browse 45+ tournaments",
    "home.trackProgress": "Track your progress and achievements",
    "home.earnAchievements": "Earn achievements",
    "home.manageTournaments": "Manage tournaments",
    "home.trackRegistrations": "Track registrations and payments",
    "home.accessAnalytics": "Access analytics",
    "home.getStarted": "Get Started",
    "home.learnMore": "Learn More",
    "home.readyToStart": "Ready to start?",
    "home.joinThousands": "Join thousands of students and organizers on the premier Olympiad platform for Mongolia",
    "home.chooseYourPath": "Choose Your Path",
    "home.students": "Students",
    "home.tournaments": "Tournaments",
    "home.organizers": "Organizers",
    "home.activeEvents": "Active Events",
    "home.registrationFee": "Registration Fee",
    "home.easyRegistration": "Easy registration process",
    "home.trackAchievements": "Track your achievements",
    "home.createUnlimited": "Create unlimited events",
    "home.manageRegistrations": "Manage registrations",
    "home.analyticsDashboard": "Analytics dashboard",
    "home.createAccount": "Create Account",
    "home.readyToGetStarted": "Ready to Get Started?",
    
    // Student Dashboard
    "student.title": "Student Dashboard",
    "student.welcome": "Welcome",
    "student.availableTournaments": "Available Tournaments",
    "student.myRegistrations": "My Registrations",
    "student.categories": "Categories",
    "student.allCategories": "All Categories",
    "student.search": "Search tournaments...",
    "student.noTournaments": "No tournaments found",
    "student.noRegistrations": "No registrations yet",
    "student.noRegistrationsDesc": "Browse available tournaments and register",
    "student.tryDifferentSearch": "Try a different search",
    "student.registered": "Registered",
    "student.full": "Full",
    "student.details": "Details",
    "student.register": "Register",
    "student.unregister": "Cancel Registration",
    "student.finished": "Finished",
    "student.confirmUnregister": "Cancel registration?",
    "student.registrationFailed": "Registration failed. Tournament may be full.",
    
    // Organizer Dashboard
    "organizer.title": "Organizer Dashboard",
    "organizer.welcome": "Welcome",
    "organizer.myTournaments": "My Tournaments",
    "organizer.totalRegistrations": "Total Registrations",
    "organizer.revenue": "Revenue",
    "organizer.createTournament": "Create New Tournament",
    "organizer.noTournaments": "No tournaments yet",
    "organizer.createFirst": "Create your first tournament",
    "organizer.edit": "Edit",
    "organizer.delete": "Delete",
    "organizer.viewRegistrations": "View Registrations",
    "organizer.confirmDelete": "Delete this tournament?",
    
    // Tournament Form
    "tournament.title": "Tournament Title",
    "tournament.description": "Description",
    "tournament.category": "Category",
    "tournament.date": "Date",
    "tournament.location": "Location",
    "tournament.maxParticipants": "Max Participants",
    "tournament.registrationFee": "Registration Fee (₮)",
    "tournament.pdfFile": "Competition Material / Test (PDF)",
    "tournament.downloadMaterial": "Download Material",
    "tournament.create": "Create Tournament",
    "tournament.update": "Update",
    "tournament.cancel": "Cancel",
    
    // Tournament Detail
    "detail.tournamentDetails": "Tournament Details",
    "detail.about": "About Tournament",
    "detail.organizer": "Organizer",
    "detail.registrationInfo": "Registration Information",
    "detail.spotsLeft": "Spots Left",
    "detail.spots": "spots",
    "detail.payment": "Payment",
    "detail.status": "Status",
    "detail.open": "Open",
    "detail.closed": "Closed",
    "detail.backToDashboard": "Back to Dashboard",
    "detail.notFound": "Tournament Not Found",
    "detail.notFoundDesc": "The tournament you're looking for doesn't exist or has been deleted",
    
    // Payment Modal
    "payment.title": "Pay Registration Fee",
    "payment.tournament": "Tournament",
    "payment.amount": "Amount",
    "payment.cardNumber": "Card Number",
    "payment.expiryDate": "Expiry Date (MM/YY)",
    "payment.cvv": "CVV",
    "payment.confirmPayment": "Confirm Payment",
    "payment.processing": "Processing...",
    "payment.success": "Payment Successful!",
    "payment.successMessage": "You have been successfully registered.",
    "payment.error": "Payment Failed",
    "payment.tryAgain": "Please try again",
    
    // Auth
    "auth.studentLogin": "Student Login",
    "auth.organizerLogin": "Organizer Login",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.login": "Login",
    "auth.noAccount": "Don't have an account?",
    "auth.signupHere": "Sign up here",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.studentSignup": "Student Sign Up",
    "auth.organizerSignup": "Organizer Sign Up",
    "auth.name": "Name",
    "auth.school": "School",
    "auth.grade": "Grade",
    "auth.organization": "Organization",
    "auth.signup": "Sign Up",
    "auth.haveAccount": "Already have an account?",
    "auth.loginHere": "Login here",
    
    // Login/Signup Pages
    "login.title": "Login",
    "login.subtitle": "Log in with your account",
    "login.button": "Login",
    "login.error": "Invalid email or password",
    "login.noAccount": "Don't have an account?",
    "login.signupLink": "Sign up",
    "login.role": "User Role",
    "login.welcomeBack": "Welcome back!",
    "login.demoAccounts": "Demo accounts:",
    "login.email": "Email",
    "login.password": "Password",
    
    "signup.title": "Sign Up",
    "signup.subtitle": "Create a new account",
    "signup.button": "Sign Up",
    "signup.error": "This email is already registered",
    "signup.hasAccount": "Already have an account?",
    "signup.loginLink": "Login",
    "signup.role": "User Role",
    "signup.name": "Name",
    "signup.email": "Email",
    "signup.password": "Password",
    "signup.school": "School",
    "signup.grade": "Grade",
    "signup.organization": "Organization",
    
    // About Page
    "about.title": "About Us",
    "about.mission": "Our Mission",
    "about.missionText": "TemtseenPortal aims to provide Mongolian students with easy access to olympiad and tournament registration. We support the education sector with digital solutions and contribute to developing students' skills.",
    "about.howItWorks": "How It Works",
    "about.forStudents": "For Students",
    "about.forStudentsText": "Browse available tournaments and register with just a few clicks. Pay registration fees through our secure payment system and track your achievements.",
    "about.forOrganizers": "For Organizers",
    "about.forOrganizersText": "Create tournaments, manage participants, and track registration fees. Manage the entire process easily on one platform.",
    "about.contact": "Contact Us",
    "about.contactText": "If you have any questions or suggestions, please contact us:",
    "about.email": "Email: info@temtseenportal.mn",
    "about.phone": "Phone: +976 7000-0000",
    "about.description": "TemtseenPortal is a platform for Mongolian students to register for olympiads and tournaments. We leverage modern technology to support the education sector and enhance student skills.",
    "about.ourMission": "Our Mission",
    "about.missionDesc": "TemtseenPortal is dedicated to enhancing the skills of Mongolian students by providing easy access to olympiad and tournament registration. We aim to support the education sector with digital solutions and contribute to the development of students' abilities.",
    "about.value1": "Empowering Students",
    "about.value2": "Providing Useful Tools for Organizers",
    "about.value3": "Building a Dynamic Education Community",
    "about.students": "Students",
    "about.events": "Tournaments",
    "about.organizers": "Organizers",
    "about.coreValues": "Core Values",
    "about.coreValuesDesc": "Guiding principles of our operations",
    "about.excellence": "Excellence",
    "about.excellenceDesc": "We strive to excel in everything we do",
    "about.community": "Community",
    "about.communityDesc": "Fostering interaction between students and organizers",
    "about.innovation": "Innovation",
    "about.innovationDesc": "Continuously improving our platform with new features",
    "about.achievement": "Achievement",
    "about.achievementDesc": "Recognizing and celebrating student success",
    "about.builtForMongolia": "Built for Mongolia",
    "about.builtForMongoliaDesc": "TemtseenPortal is a platform designed for Mongolian students and educators",
    "about.joinCommunity": "Join Our Growing Community",
    "about.joinCommunityDesc": "Whether you're a student participating in tournaments or an organizer creating them, TemtseenPortal is here to support you.",
    "about.getStarted": "Get Started Today",
    "about.backHome": "Back to Home",
    
    // Footer
    "footer.copyright": "© 2026 TemtseenPortal. Olympiad and Tournament Registration System for Mongolian Students",
    
    // Profile
    "profile.title": "Profile",
    "profile.subtitle": "Edit your profile information",
    "profile.back": "Back",
    "profile.edit": "Edit",
    "profile.save": "Save",
    "profile.saveChanges": "Save Changes",
    "profile.cancel": "Cancel",
    "profile.saveSuccess": "Saved successfully!",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.school": "School",
    "profile.grade": "Grade",
    "profile.organization": "Organization",
    "profile.address": "Address",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.back": "Back",
    "notifications.unreadCount": "{count} unread notifications",
    "notifications.noUnread": "No unread notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.clearAll": "Clear all",
    "notifications.all": "All",
    "notifications.unread": "Unread",
    "notifications.markRead": "Mark as read",
    "notifications.noNotifications": "No notifications",
    "notifications.noNotificationsDesc": "You will see new notifications here",
    "notifications.confirmClear": "Clear all notifications?",
    "notifications.registrationSuccess": "Registration successful!",
    "notifications.registrationSuccessMsg": "You have been successfully registered for the tournament.",
    "notifications.tournamentReminder": "Tournament Reminder",
    "notifications.tournamentReminderMsg": "Your tournament starts in 3 days.",
    "notifications.paymentPending": "Payment pending",
    "notifications.paymentPendingMsg": "Your registration payment is pending.",
    "notifications.tournamentCreated": "Tournament Created",
    "notifications.tournamentCreatedMsg": "Your tournament has been successfully created.",
    
    // Achievements
    "achievements.title": "My Achievements",
    "achievements.subtitle": "Your olympiad and tournament history",
    "achievements.back": "Back",
    "achievements.total": "Total",
    "achievements.gold": "Gold",
    "achievements.silver": "Silver",
    "achievements.bronze": "Bronze",
    "achievements.avgPlace": "Average Place",
    "achievements.allCategories": "All Categories",
    "achievements.noAchievements": "No achievements yet",
    "achievements.noAchievementsDesc": "Participate in tournaments to earn achievements",
    "achievements.first": "1st Place",
    "achievements.second": "2nd Place",
    "achievements.third": "3rd Place",
    "achievements.place": "Place",
    "achievements.participants": "Participants",
    "achievements.score": "Score",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("mn");

  // Load language preference from localStorage on mount
  useEffect(() => {
    const savedLanguage = getLocalStorage("temtseen_language");
    if (savedLanguage === "mn" || savedLanguage === "en") {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language preference to localStorage when it changes
  useEffect(() => {
    setLocalStorage("temtseen_language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}